# NumPy Practice
## Sirui Ren
One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large data sets in Python.

In [1]:
import numpy as np

## Creating ndarrays
### Create an array from a list of strings

In [2]:
data1 = ['a', 'b', 'c']
np.array(data1)  # array is a function

array(['a', 'b', 'c'], 
      dtype='<U1')

### An array of 5 zeros

In [3]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

### An array of 5 ones

In [4]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

### An empty array
Values are not initialized to any particular value.

In [5]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

### <i>arange()</i> function

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(3, 10, 2) #start, end, step

array([3, 5, 7, 9])

### <i>linspace()</i> function 

In [8]:
np.linspace(0, 6, 4)  # start, end, number of points

array([ 0.,  2.,  4.,  6.])

## Two-dimensional arrays
### Create an array from a list of equal-length lists.

In [9]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Display a number of dimensions with <i>ndim</i>


In [10]:
arr.ndim

2

### The shape of an array indicates the size of each dimension

In [11]:
arr.shape

(2, 4)

### The datatype of our array

In [12]:
arr.dtype

dtype('int64')

## Three-dimensional arrays
### 2 arrays, 3 rows and 2 columns

In [13]:
arr3d = np.empty((2, 3, 2))
arr3d

array([[[ -2.31584178e+077,  -2.31584178e+077],
        [  3.95252517e-323,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [14]:
arr3d.ndim

3

In [15]:
arr3d.shape

(2, 3, 2)

### Create a three-dimensional array: 10 arrays, 3 rows and 2 columns:

In [16]:
my_arr = np.zeros((10, 3, 2))
my_arr

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [17]:
my_arr.ndim

3

In [18]:
my_arr.shape

(10, 3, 2)

## Operations between Arrays and Scalars
Arithmetic operations with scalars propogate the value to each element.

### Vectorization
is the ability to perform batch operations on data without writing any for loops.



In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [21]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [22]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

## Array Basic Indexing and Slicing
Array slices are VIEWS on the original array.

In [23]:
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### On the surface, array work similar to lists:

In [24]:
my_arr[2]

2

In [25]:
my_arr[2:5]

array([2, 3, 4])

In [2]:
### The following example is different from the list: the original source array is modified (would not work for a list).

In [3]:
### Assign a scalar to a slice of an array.  The value will be propataged to the entire selection.

In [26]:
my_arr[2:5] = 100

In [4]:
### An original array is modified

In [27]:
my_arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9])

### Two-dimensional array slicing and indexing

In [28]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### The element at each index is not a scalar, but a one-dimensional array:

In [29]:
arr2d[0]

array([1, 2, 3])

### Two ways to select an individual element:

In [30]:
arr2d[0][1]

2

In [31]:
arr2d[0, 1]

2

### Indexing elements in a NumPy array
<table>
<tr><td>0, 0</td><td>0, 1</td><td>0, 2</td></tr>
<tr><td>1, 0</td><td>1, 1</td><td>1, 2</td></tr>
<tr><td>2, 0</td><td>2, 1</td><td>2, 2</td></tr>
</table>

### Three-dimensional array slicing and indexing

In [32]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
arr3d.ndim

3

In [34]:
arr3d.shape

(2, 2, 3)

In [35]:
# first index returns a two-dimensional array
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr3d[0].shape

(2, 3)

In [37]:
# second index returns a one-dimensional array
arr3d[0][0]

array([1, 2, 3])

In [38]:
arr3d[0][0].shape

(3,)

In [39]:
# third index returns a scalar
arr3d[0][0][0]

1

In [40]:
arr3d[0][0][0].shape

()

### Assigning scalar values to our slices

In [41]:
# update a scalar value
arr3d[0][0][0] = -1
arr3d

array([[[-1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
# update a one-dimensional array 
arr3d[0][0] = -1
arr3d

array([[[-1, -1, -1],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
# update a two-dimensional array 
arr3d[0] = -1
arr3d

array([[[-1, -1, -1],
        [-1, -1, -1]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
# to update a three-dimensional array:
arr3d[:] = -1
arr3d

array([[[-1, -1, -1],
        [-1, -1, -1]],

       [[-1, -1, -1],
        [-1, -1, -1]]])

### Assigning an array to a slice of array

In [45]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
#update our 3d array
arr3d[0] = -1
arr3d

array([[[-1, -1, -1],
        [-1, -1, -1]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
#update our 3d array back to old values
arr3d[0] = old_values

In [49]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### 2nd example: using an array to update a slice of our array

In [50]:
arr3d[1][0]

array([7, 8, 9])

In [51]:
arr3d[1][0] = np.array([-100, -100, -100])
arr3d

array([[[   1,    2,    3],
        [   4,    5,    6]],

       [[-100, -100, -100],
        [  10,   11,   12]]])

## Indexing with slices
### Slicing a one-dimensional array

In [52]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# Index 0 through 3 (index 0 is included, index 3 is not included)
arr[0:3]

array([0, 1, 2])

### Slicing a two-dimensional array

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Slicing along axis 0, the first axis.<br/>
A slice selects a range of elements along an axis.

In [55]:
# Selects rows 0 and 1 (2 is not included)
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

<b>Select the following slice:</b><br/>
- rows with index 0 and 1 (2 is not included).<br/>
- columns with index 1 and 2

In [56]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

<b>Select the following slice:</b> <br/>
- row with index 1
- columns with index 0 and 1

In [57]:
arr2d[1, :2]

array([4, 5])

<b>Select the following slice:</b>
- row with index 2
- column with index 0

In [58]:
arr2d[2, :1]

array([7])

<b>Select the following slice:</b>
- all rows
- column with index 0

In [59]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

## Boolean Indexing
### <i>names</i> is an array of names with duplicates 

In [60]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

### <i>data</i> is normally distributes random data.

In [61]:
data = np.random.randn(7, 4)
data

array([[ 0.68029351, -0.8032741 , -0.20736104,  0.19575939],
       [ 0.44348878, -1.27746613, -0.60752743, -1.19113178],
       [-0.51757744,  0.10984078, -0.28788516, -1.75744544],
       [ 0.39272788,  0.81931732,  0.09329659, -0.64333727],
       [ 1.45373535, -0.33841286,  0.47058435,  1.06202956],
       [-0.95732021,  0.55271795,  1.12570743,  0.34931764],
       [-0.66943437, -1.57559736, -1.1712038 , -1.19336642]])

### Comparing <i>names</i> with the string 'Bob' yields a boolean array:

In [62]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

### This boolean array can be passed when indexing the array:

In [63]:
data[names == 'Bob']

array([[ 0.68029351, -0.8032741 , -0.20736104,  0.19575939],
       [ 0.39272788,  0.81931732,  0.09329659, -0.64333727]])